# Original work (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017-2018.
# Modified work (c) William Belle, 2018-2019.
# See the LICENSE file for more details.

language: node_js
node_js:
  - "11"
  - "10"
  - "8"
after_success:
  - npm install coveralls mocha-lcov-reporter
  - npm run coveralls
