# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017.
# See the LICENSE file for more details.

language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
after_success:
  - npm install coveralls mocha-lcov-reporter
  - npm run coveralls
