# Original work (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017-2018.
# Modified work (c) William Belle, 2018-2020.
# See the LICENSE file for more details.

language: node_js
node_js:
  - "14"
  - "13"
  - "12"
  - "10"
after_success:
  - npm install coveralls mocha-lcov-reporter
  - npm run coveralls
