# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017-2018.
# See the LICENSE file for more details.

language: node_js
node_js:
  - "10"
  - "9"
  - "8"
after_success:
  - npm install coveralls mocha-lcov-reporter
  - npm run coveralls
